---
title: "viz_scripts"
output: html_document
date: "2024-05-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse)
```


#load all .csv files in the simulated data folder
```{r}
setwd("../Python/simulated_data/")

files <- list.files(pattern = "*.csv", full.names = TRUE)

#load  all .csv files
data <- lapply(files, read_csv)

#split it to single dfs with the correct names
names(data) <- gsub(".csv", "", list.files(pattern = "*.csv"))

#Split to single dfs
list2env(data, envir = .GlobalEnv)

#Check if it worked
print(ls())


#get the resistance level from the full data frame
single_trial_resistance_beliefs <- single_trial_resistance_beliefs %>%
  mutate(resistance_level = single_trial_full_data$resistance_state,
         #get entropy levels
         resistance_entropy = single_trial_full_data$resistance_entropy,
         #make a timestep column
         timestep = 1:nrow(single_trial_resistance_beliefs) - 1)  %>% 
  #select all but the first column
 select(c(-1)) 

#Turn into long format
single_trial_resistance_beliefs <- single_trial_resistance_beliefs %>%
 pivot_longer(cols = c(1:6), values_to = "belief")  %>% 
  mutate(state_belief = as.numeric(gsub("r", "", name)) - 1)

#make full data have a timestep column
single_trial_full_data <- single_trial_full_data %>%
  mutate(timestep = 1:nrow(single_trial_full_data) - 1)


```
# Overall plot settings
```{r}
theme_set(theme_minimal())
```


# Single level plots
##Show trial level data
```{r}
#first build treatment dataframe for when treatment is given
treatment_shading <- single_trial_full_data %>%
  filter(treatment_state == "treat") %>% 
  select(timestep) %>%
  
  #make a new column for used for plotting
  mutate(time_plus_1 = timestep + 1,
         timestep_minus_1 = timestep - 1)


ggplot(single_trial_full_data, aes(x = timestep, y = tumor_state)) +
  
  #add line for tumor
  geom_line(aes(color = "Tumor Level")) +
  
  #add line for resistance state
  geom_line(aes(y = resistance_state, color = "Resistance Level" ), linetype = 2) +

  #add shaded areas for treatment on
  geom_rect(data = treatment_shading, aes(xmin = timestep_minus_1, xmax = timestep,  ymin = -Inf, ymax = Inf, fill = "Treatment Is Given"), inherit.aes = FALSE, , alpha = 0.4, label = "Treatment is given")  +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL),
         colour = guide_legend(title = NULL)) +
  
  labs(title = "Tumor and Resistance Level Through Time",
         x = "Time",
         y = "Tumor and Resistance State")

#save plot 
ggsave("../visualizations/Tumor_and_Resistance_Levels.png", width = 10, height = 6, units = "in")

```


## Show that resistance level is learned through time

```{r}
#Plot the resistance level through time as x-axis
ggplot(single_trial_resistance_beliefs, aes(y = resistance_level, x = timestep)) +

  #plot actual level as empty cicles
  geom_line(linetype = 2) +
  ylim(0, 5) +
  
  #plot the belief as colored and sized points according to beleif strength
  geom_point(aes(y = state_belief, color = belief, size = belief), shape = 21) +
  
  #add color scheme
  scale_color_gradient(low = "blue", high = "red") +
  scale_size(range = c(0.001, 7)) +
  
  guides(size = "none") +
  
  #add the model belief as colored plot depeding on probability
  labs(title = "Model Beliefs of Resistance Level",
       x = "Time",
       y = "Resistance State",
       color = "Probability According to Model") 
 
ggsave("../visualizations/Model_Beliefs_about_Resistance.png", width = 10, height = 6, units = "in")
```
# Make a plot of sim lengths

## first make a database containing all the lengths
```{r}
#Maunally add growth rate data ** should be added in simulation instead along other sim parameters **
sim_lengths_growth_rate_0.1$growth_rate <- 0.1
sim_lengths_growth_rate_0.3$growth_rate <- 0.3
sim_lengths_growth_rate_0.5$growth_rate <- 0.5
sim_lengths_growth_rate_0.7$growth_rate <- 0.7

#add the rows of all of them to one dataframe
sim_lengths <- rbind(sim_lengths_growth_rate_0.1, sim_lengths_growth_rate_0.3, sim_lengths_growth_rate_0.5, sim_lengths_growth_rate_0.7) 

#turn into long format
sim_lengths_long <- sim_lengths %>% 
  select(-1) %>% 
  pivot_longer(cols = 1:4, names_to = "strategy", values_to = "sim_length")


#make density curves for simulation
ggplot(sim_lengths_long, aes(x = sim_length, fill = strategy, color = strategy)) +
  geom_density(alpha = 0.1) + 
  facet_wrap(~growth_rate) +
  labs(title = "POMDP performance against ADT",
       x = "Simulation Length",
       y = "Density") 

ggsave("../visualizations/Simulation_Lengths_full.png", width = 10, height = 6, units = "in")

```
## plot contrasted sim lengths
```{r}

#make a df for contrasts
contrasted_sim_lengths <- sim_lengths %>%
  
  filter(growth_rate != 0.1) %>%
  
  #make growth rate a factor
  mutate(growth_rate = as.factor(growth_rate),
         short_vs_adt = Short - ADT,
         medium_vs_adt = Medium - ADT,
         long_vs_adt = Long - ADT) %>% 
  
  #pivot to long format for ease of plotting
  pivot_longer(cols = contains("vs"), values_to = "sim_length", names_to = "contrast") %>% 
  
  #only keep usefull columns
  select(contrast, sim_length, growth_rate)


#plot histograms of sim lengths and facet by growth rate
ggplot(contrasted_sim_lengths, aes(x = sim_length, fill = contrast, color = contrast)) +
  geom_density(alpha = 0.1) +
  xlim(-75, 75) +
  facet_wrap(~growth_rate) +
  labs(title = "POMDP performance against ADT",
       x = "Simulation Length",
       y = "Density")

ggsave("../visualizations/Simulation_Lengths_contrasted_full.png", width = 10, height = 6, units = "in")

#create a subset for 
contrasted_sim_lengths %>%
  filter(growth_rate != 0.1 & contrast == "long_vs_adt") %>% 

#plot histograms of sim lengths and facet by growth rate
ggplot(aes(x = sim_length)) +
  geom_density(aes(fill = "long_vs_adt", color = "long_vs_adt"), alpha = 0.7) + 
  facet_wrap(~growth_rate) +
  xlim(-75,75) +
  
  #plot a vertical line at 0
  geom_vline(xintercept = 0, linetype = 2) +

  labs(title = "POMDP performance against ADT",
       x = "Difference in length of simulation between POMDP and Range Bounded Strategy",
       y = "Density") 


ggsave("../visualizations/Simulation_Lengths_contrasted_long_no_low.png", width = 10, height = 6, units = "in")
```


